---
apiVersion: v1
kind: Secret
metadata:
  name: pg-config
  labels:
    app.kubernetes.io/part-of: docker-voting
    app.kubernetes.io/version: "1.0.0"
type: Opaque
stringData:
  pg-user: postgres
  pg-pass: postgres
...