---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: docker-voting
    app.kubernetes.io/version: "1.0.0"
spec:
  ports:
  - port: 6379
  selector:
    app: docker-voting
    run: redis
    tier: backend
    env: production
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: docker-voting
    app.kubernetes.io/version: "1.0.0"
spec:
  selector:
    matchLabels:
      app: docker-voting
      run: redis
      tier: backend
      env: production
  replicas: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 20%
      maxSurge: 20%
  template:
    metadata:
      labels:
        app: docker-voting
        run: redis
        tier: backend
        env: production
    spec:
      containers:
      - image: redis:6
        name: redis-ctr
        resources:
          requests:
            memory: 10Mi
            cpu: 30m
          limits:
            memory: 250Mi
            cpu: 150m
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 1
          periodSeconds: 20
          timeoutSeconds: 3
...