---
apiVersion: v1
kind: Service
metadata:
  name: result
  labels:
    app: docker-voting
spec:
  ports:
  - name: result-http
    port: 80
  selector:
    app: docker-voting
    run: result
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
  labels:
    app: docker-voting
spec:
  selector:
    matchLabels:
      app: docker-voting
      run: result
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 20%
      maxSurge: 20%
  template:
    metadata:
      labels:
        app: docker-voting
        run: result
    spec:
      containers:
      - image: ajagnic/voting_fixed_result:v1
        name: result-ctr
        env:
        - name: OPTION_A
          valueFrom:
            configMapKeyRef:
              name: voting-env
              key: option_a
        - name: OPTION_B
          valueFrom:
            configMapKeyRef:
              name: voting-env
              key: option_b
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: pg-config
              key: pg-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-config
              key: pg-pass
        ports:
        - containerPort: 80
          name: result-ctr-port
        resources:
          requests:
            memory: 25Mi
            cpu: 50m
          limits:
            memory: 150Mi
            cpu: 200m
        readinessProbe:
          tcpSocket:
            port: result-ctr-port
          initialDelaySeconds: 1
          periodSeconds: 5
          timeoutSeconds: 2
...