---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress
---
apiVersion: v1
kind: LimitRange
metadata:
  name: ingress-limits
  namespace: ingress
spec:
  limits:
  - default:
    min:
      memory: 500Mi
      cpu: 500m
    type: Container
---
apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: ingress
spec:
  type: LoadBalancer
  ports:
  - name: web
    port: 80
  selector:
    app: traefik
    run: ingress-controller
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-admin
  namespace: ingress
spec:
  type: NodePort
  ports:
  - name: admin
    port: 8080
  selector:
    app: traefik
    run: ingress-controller
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: traefik
  namespace: ingress
spec:
  selector:
    matchLabels:
      app: traefik
      run: ingress-controller
  template:
    metadata:
      labels:
        app: traefik
        run: ingress-controller
    spec:
      serviceAccountName: traefik-sa
      containers:
      - image: traefik:1.7
        name: traefik-ctr
        args:
        - --api
        - --kubernetes
        securityContext:
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-sa
  namespace: ingress
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: traefik-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-cr
subjects:
- kind: ServiceAccount
  name: traefik-sa
  namespace: ingress
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: traefik-cr
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - ingresses/status
  verbs:
  - update
...